"""
Mock runtime for the generate_prd skill.

Stands in for the real n8n workflow (fetch Jira epics + Confluence pages,
build a prompt, call the LLM) so we can test router -> execution plan ->
skill output end to end before M4 (real MCP integration) exists.

NOTE (POC build): the running platform now dispatches generate_prd to a real
n8n workflow that calls Claude with the Atlassian + GitHub MCP servers via
agentgateway. This module is only used when OFFLINE_MODE is set, so the stack
can be smoke-tested end to end without an ANTHROPIC_API_KEY or live MCP servers.
"""
from datetime import date


MOCK_JIRA_EPICS = [
    {"key": "ATLAS-101", "summary": "Customer notification preferences service"},
    {"key": "ATLAS-102", "summary": "Real-time delivery pipeline"},
]

MOCK_CONFLUENCE_PAGES = [
    {"title": "Atlas - Vision Doc", "excerpt": "Unify notification channels across SMS, email, push."},
]


def extract_project_name(message: str) -> str:
    """Very small helper: pulls the word after 'for project' or 'for' if present."""
    lowered = message.lower()
    # Strip trailing punctuation so "project Atlas?" -> "Atlas" (matches the stored name).
    trailing = " .?!,;:\"'"
    if "for project" in lowered:
        return message.split("for project", 1)[1].strip().strip(trailing).title()
    if " for " in lowered:
        return message.split(" for ", 1)[1].strip().strip(trailing).title()
    return "Untitled Project"


def run(message: str) -> dict:
    """Mimics the skill runtime: gather context (mocked), 'call the LLM' (canned), return markdown."""
    project_name = extract_project_name(message)

    epics_md = "\n".join(f"- **{e['key']}**: {e['summary']}" for e in MOCK_JIRA_EPICS)
    pages_md = "\n".join(f"- **{p['title']}**: {p['excerpt']}" for p in MOCK_CONFLUENCE_PAGES)

    markdown = f"""# PRD: {project_name}
*Draft generated {date.today().isoformat()} — mock run, no live Jira/Confluence data*

## Summary
This is a mock PRD generated by the vertical-slice test harness. Once M4 lands,
this section will be written by the LLM from real Jira/Confluence context instead
of the canned data below.

## Context pulled (mocked)

**Jira epics:**
{epics_md}

**Confluence pages:**
{pages_md}

## Status
⚠️ Pending human approval (requires_approval = true for this skill)
"""
    return {"project_name": project_name, "output_markdown": markdown}


if __name__ == "__main__":
    result = run("create a PRD for project Atlas")
    print(result["output_markdown"])
